[profiles]
default=nextredos

[profile_nextredos]
name=NextRedOS
background-color=#000000
foreground-color=#FF0000
palette=#000000:#CC0000:#00CC00:#CCCC00:#0000CC:#CC00CC:#00CCCC:#CCCCCC:#555555:#FF0000:#00FF00:#FFFF00:#5555FF:#FF55FF:#55FFFF:#FFFFFF
bold-color=#FF0000
use-theme-colors=false
use-system-font=false
font=Monospace 10
scrollback-lines=10000
