[greeter]
background=/usr/share/backgrounds/NextRedOS/wallpaper.png
theme-name=BlackMATE
icon-theme-name=Papirus-Dark
font-name=Noto Sans 11
xft-antialias=true
xft-dpi=96
xft-hintstyle=slight
xft-rgba=rgb
show-clock=true
clock-format=%H:%M - %d/%m/%Y
indicators=~host;~spacer;~clock;~spacer;~power
position=50%,center 50%,center
panel-position=bottom
logo=/usr/share/pixmaps/nextredos-logo.png
